const quranData = {
    "جزء عم": [
        { name: "النبأ", url: "https://files.catbox.moe/50is73.opus" },
        { name: "النازعات", url: "/Quran_.html/آلَنِبًآء .mp3" },
        { name: "عبس", url: "/Quran_.html/النباء .mp3" },
        { name: "التكوير", url: "" },
        { name: "الانفطار", url: "" },
        { name: "المطففين", url: "" },
        { name: "الانشقاق", url: "" },
        { name: "البروج", url: "" },
        { name: "الطارق", url: "" },
        { name: "الأعلى", url: "" },
        { name: "الغاشية", url: "" },
        { name: "الفجر", url: "" },
        { name: "البلد", url: "" },
        { name: "الشمس", url: "" },
        { name: "الليل", url: "" },
        { name: "الضحى", url: "" },
        { name: "الشرح", url: "" },
        { name: "التين", url: "" },
        { name: "العلق", url: "" },
        { name: "القدر", url: "" },
        { name: "البينة", url: "" },
        { name: "الزلزلة", url: "" },
        { name: "العاديات", url: "" },
        { name: "القارعة", url: "" },
        { name: "التكاثر", url: "" },
        { name: "العصر", url: "" },
        { name: "الهمزة", url: "" },
        { name: "الفيل", url: "" },
        { name: "قريش", url: "" },
        { name: "الماعون", url: "" },
        { name: "الكوثر", url: "" },
        { name: "الكافرون", url: "" },
        { name: "النصر", url: "" },
        { name: "المسد", url: "" },
        { name: "الإخلاص", url: "" },
        { name: "الفلق", url: "" },
        { name: "الناس", url: "" }
    ],
    "جزء تبارك": [
        { name: "الملك", url: "" },
        { name: "القلم", url: "" },
        { name: "الحاقة", url: "" },
        { name: "المعارج", url: "" },
        { name: "نوح", url: "" },
        { name: "الجن", url: "" },
        { name: "المزمل", url: "" },
        { name: "المدثر", url: "" },
        { name: "القيامة", url: "" },
        { name: "الإنسان", url: "" },
        { name: "المرسلات", url: "" }
    ],
    "جزء قد سمع": [
        { name: "المجادلة", url: "" },
        { name: "الحشر", url: "" },
        { name: "الممتحنة", url: "" },
        { name: "الصف", url: "" },
        { name: "الجمعة", url: "" },
        { name: "المنافقون", url: "" },
        { name: "التغابن", url: "" },
        { name: "الطلاق", url: "" },
        { name: "التحريم", url: "" }
    ],
    "قال فما خطبكم": [
        { name: "الذاريات", url: "" },
        { name: "الطور", url: "" },
        { name: "النجم", url: "" },
        { name: "القمر", url: "" },
        { name: "الرحمن", url: "" },
        { name: "الواقعة", url: "" },
        { name: "الحديد", url: "" }
    ]
};

